AWSTemplateFormatVersion: 2010-09-09
Description: >-
  REST API on a LAMPy stack

Resources:
  VPC:
    Type: 'AWS::EC2::VPC'
    Properties:
      CidrBlock: 10.0.0.0/16
      Tags:
        - Key: Name
          Value: lampy-vpc

  WebServerSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Allow HTTP traffic
      VpcId: !Ref VpcId # can i reference a value within a block?
      SecurityGroupIngress:
        - InProtocol: tcp
          FromPort: '80'
          ToPort: '80'
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - InProtocol: tcp
          FromPort: '3306'
          ToPort: '3306'
          CidrIp: '10.0.0.0/16' # VPC CIDR

  # WebServerInstance:
  #   Type: 'AWS::EC2::Instance'
  #   Metadata:
  #     'AWS::CloudFormation::Init':
  #       configSets:
  #         InstallAndRun:
  #           - Install
  #           - Configure
  #         Install:
  #           packages:
  #             yum:
  #               mysql: []
  #               mysql-server: []
  #               mysql-libs: []
  #               httpd: []
