AWSTemplateFormatVersion: 2010-09-09
Description: >-
  REST API on a LAMPy stack

Resources:
  VPC:
    Type: 'AWS::EC2::VPC'
    Properties:
      CidrBlock: 10.0.0.0/16
      Tags:
        - Key: Name
          Value: lampy-vpc

  IGW:
    Type: 'AWS::EC2::InternetGateway'
    Properties:
      Tags:
        - Key: Name
          Value: lampy-igw

  VPC-GW-Attachment:
    Type: 'AWS::EC2::VPCGatewayAttachment'
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref IGW

  WSSubnet:
    Type: 'AWS::EC2::Subnet'
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.0.0.0/24
      AvailabilityZone: 'ap-southeast-2a'
      Tags:
        - Key: Name
          Value: ws-public-az-a

  DBSubnet:
    Type: 'AWS::EC2::Subnet'
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.0.1.0/24
      AvailabilityZone: 'ap-southeast-2a'
      Tags:
        - Key: Name
          Value: db-private-az-a

  WSSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Allow HTTP traffic
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '80'
          ToPort: '80'
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: tcp
          FromPort: '3306'
          ToPort: '3306'
          CidrIp: '10.0.0.0/16' # VPC CIDR
      Tags:
        - Key: Name
          Value: ws-sg

  DBSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Allow web servers to access the DB
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '3306'
          ToPort: '3306'
          CidrIp: 10.0.0.0/16 # VPC CIDR
      Tags:
        - Key: Name
          Value: db-sg

  # WebServerInstance:
  #   Type: 'AWS::EC2::Instance'
  #   Metadata:
  #     'AWS::CloudFormation::Init':
  #       configSets:
  #         InstallAndRun:
  #           - Install
  #           - Configure
  #         Install:
  #           packages:
  #             yum:
  #               mysql: []
  #               mysql-server: []
  #               mysql-libs: []
  #               httpd: []
